### ISSUE TITLE
Add ability to Limit Image Count Processed at Any One Time

### ISSUE THREAD

**Issue by tekwizz123** [MohrJonas/obsidian-ocr#6]
Right now I have a lot of images in my vault from various talks, meetings, things I've gathered from the internet, etc. This results in 800 instances of image processing all trying to load at the same time, one for each image. This ends up basically making the entire computer (a gaming machine at that) pretty much go to a crawl with apps beyond Obsidian not really responding. Because these are processes outside of Obsidian, unloading the plugin doesn't help things, you have to close down Obsidian in its entirety when you do eventually get the chance.

This should be fixed to avoid immediately overloading the computer's memory and CPU and basically trying to make it go Mad Max at loadup 😄 I think it would be reasonable to do maybe 10-15 images at a time and slowly work your way through the lot based on that. If this option could be configurable that would be even better to help low end machines use the plugin more effectively.

**Comment by evilgeniuschronicles** [comment]
I was just about to start tackling this for Hacktoberfest. Once I got this working on my Linux machine it immediately made it fall over with 50 simultaneous tesseract processes. I'm glad I checked in and saw this was already in process before I started building a queue and processor.

**Comment by evilgeniuschronicles** [comment]
I have the same issue on my Linux laptop. I'm experimenting with using the async module to have a limited queue working. I will submit a PR if/when I get that working.

**Comment by evilgeniuschronicles** [comment]
@tekwizz123 You may have a beefier machine than me with more processors. Although limiting this to say 5 kept it from falling over, I found that 3 concurrent tesseract processes was the max before it began to be slower. 

I do have one problem in what I submitted in the PR in the slider. The onChange() handler changes the queue size. If you have a small number and drag it accidentally high while you have a queue, it will set the queue to the higher number, let that many through and then have to chug through them until it falls back down to the new concurrent limit. I may see if I can fix that later. Selfishly, I may want that in a different PR since I am angling for 4 of them for Hacktoberfest.

**Comment by MohrJonas** [comment]
This problem is now fixed thanks to @evilgeniuschronicles's PR, allowing you to limit the number of concurrent processes.
Bbtw @evilgeniuschronicles I fully understand you trying to get the 4 PRs 😁
